// Central story data used across all pages.
// Updating this array automatically updates the homepage and topic pages.
window.STORIES = [
  {
    id: "algorithmic_layoff_tax",
    topic: "policy",
    label: "Policy",
    title: "The Friction of Progress: Unpacking the Algorithmic Layoff Tax | The Policy Ledger",
    url: "news/algorithmic_layoff_tax.html",
    summary: "Algorithmic Layoff Tax in the Age of AI: A detailed analysis of the newly ratified Algorithmic Layoff Tax 2026, examining the economic impact of the automation displacement threshold and corporate compliance strategies.",
    author: "",
    date: "Mar 11, 2026",
  },
  {
    id: "corporate_sustainability_disclosure_rules",
    topic: "policy",
    label: "Policy",
    title: "Navigating Corporate Sustainability Disclosure Rules | The European Compliance Review",
    url: "news/corporate_sustainability_disclosure_rules.html",
    summary: "An in-depth analysis of how new Corporate Sustainability Disclosure Rules impact mid-sized European companies, focusing on double materiality and compliance scope bands.",
    author: "",
    date: "Mar 11, 2026",
  },
  {
    id: "biodegradable_fungus_based_plastic",
    topic: "policy",
    label: "Policy",
    title: "Policy Debates Grow Around Legal Frameworks for Fungus-Based Bioplastics",
    url: "news/Biodegradable-Fungus-Based-Plastic.html",
    summary: "IRENA Assembly 2026 and Biodegradable Fungus-Based Plastic: An editorial-style policy analysis exploring how discussions linked to the IRENA Assembly have intensified debate around legal classification and regulation of biodegradable fungus-based plastic materials.",
    author: "",
    date: "Mar 11, 2026",
  },
  {
    id: "moneyledger_budget_ai_pilot",
    topic: "business",
    label: "Business",
    title: "Inside the New Push for AI-Powered Public Spending Transparency (Singapore Budget 2026)",
    url: "news/MoneyLedger-Budget-AI-Pilot.html",
    summary: "MoneyLedger Budget-AI Pilot: An in-depth editorial analysis of how a Singapore-based startup plans to build a live AI system to monitor public spending efficiency under Budget 2026, and what it could mean for accountability and innovation.",
    author: "",
    date: "Mar 11, 2026",
  },
  {
    id: "continuous_identity_verification_model",
    topic: "tech",
    label: "Tech",
    title: "Continuous Identity Verification Models: Why Enterprises Are Rechecking Identity All the Time",
    url: "news/Continuous-Identity-Verification-Model.html",
    summary: "A deep technical explainer on Continuous Identity Verification Model architectures and why enterprise systems are adopting continuous identity and device trust checks by default.",
    author: "",
    date: "Mar 11, 2026",
  },
  {
    id: "bbm_style_relay_messaging",
    topic: "tech",
    label: "Tech",
    title: "The Return of Relay Messaging? Why BBM-Style Architecture Is Back in Security Conversations",
    url: "news/BBM-Style-Relay-Messaging.html",
    summary: "A deep-dive technology feature exploring how 'BBM-style relay messaging models' are reappearing in modern secure chat discussions, focusing on server-relay routing, IP masking, and audited message hops.",
    author: "",
    date: "Mar 11, 2026",
  },
  {
    id: "biometric_passports_road_safety",
    topic: "tech",
    label: "Tech",
    title: "Biometric Integration in Modern Traffic Enforcement | Global Tech Review",
    url: "news/biometric-passports-road-safety.html",
    summary: "An in-depth analysis of how the integration of biometric passport data with urban surveillance infrastructure is revolutionizing road safety and DUI prevention.",
    author: "",
    date: "Mar 11, 2026",
  },
  {
    id: "investment_outcome_profit",
    topic: "business",
    label: "Business",
    title: "Explained: What “Investment Outcome Profit” Means in Modern Business Reporting",
    url: "news/Investment-Outcome-profit.html",
    summary: "A clear editorial-style explainer unpacking the business reporting term 'Investment Outcome profit' and how companies use it to evaluate project value relative to total inputs.",
    author: "",
    date: "Mar 11, 2026",
  },
];
