// Central story data used across all pages.
// Updating this array automatically updates the homepage and topic pages.
window.STORIES = [
//   {
//     id: "news1",
//     topic: "tech",
//     label: "Tech",
//     title: "Open hardware is coming for smartphone chips",
//     url: "news1.html",
//     summary: "From silicon supply chains to open-source design, the new wave of chipmaking is rewriting who gets to build the platforms we all depend on.",
//     author: "Samir Patel",
//     date: "Mar 10, 2026",
//   },
//   {
//     id: "news2",
//     topic: "policy",
//     label: "Policy",
//     title: "What the new privacy law means for small publishers",
//     url: "news2.html",
//     summary: "As regulators push transparency, local newsrooms must decide how to comply without sacrificing the rapport they've built with readers.",
//     author: "Ada Crow",
//     date: "Mar 9, 2026",
//   },
//   {
//     id: "news3",
//     topic: "health",
//     label: "Health",
//     title: "A hospital's quiet overhaul that cut wait times in half",
//     url: "news3.html",
//     summary: "How a systems-thinking approach to staffing and scheduling helped one emergency department manage spikes without hiring dozens more nurses.",
//     author: "Nina Lopez",
//     date: "Mar 9, 2026",
//   },
//   {
//     id: "news4",
//     topic: "business",
//     label: "Business",
//     title: "Why corporate boards are waking up to climate risk",
//     url: "news4.html",
//     summary: "Investor pressure and new accounting rules are forcing companies to reckon with supply chain disruption and stranded assets.",
//     author: "Kai Morgan",
//     date: "Mar 8, 2026",
//   },
//   {
//     id: "news5",
//     topic: "legal",
//     label: "Legal",
//     title: "A court precedent that could reshape digital speech",
//     url: "news5.html",
//     summary: "As judges parse content moderation laws, a single ruling may decide whether platforms are treated like publishers or utilities.",
//     author: "Jordan Reed",
//     date: "Mar 7, 2026",
//   },
];
